# Generated by Django 3.2.8 on 2021-11-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moradias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moradia',
            name='imagem1',
            field=models.ImageField(upload_to='imoveis'),
        ),
        migrations.AlterField(
            model_name='moradia',
            name='imagem2',
            field=models.ImageField(upload_to='imoveis'),
        ),
        migrations.AlterField(
            model_name='moradia',
            name='imagem3',
            field=models.ImageField(upload_to='imoveis'),
        ),
    ]
