# Generated by Django 3.2.8 on 2021-11-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moradias', '0002_auto_20211122_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
