# Generated by Django 3.2.6 on 2021-11-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moradias', '0004_auto_20211123_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moradia',
            name='imagem1',
        ),
        migrations.RemoveField(
            model_name='moradia',
            name='imagem2',
        ),
        migrations.RemoveField(
            model_name='moradia',
            name='imagem3',
        ),
        migrations.AddField(
            model_name='imagem',
            name='imovel',
            field=models.IntegerField(null=True),
        ),
    ]
