# Generated by Django 3.2.8 on 2021-11-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moradias', '0005_auto_20211128_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='moradia',
            name='dono',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='arquivo',
            field=models.FileField(upload_to='imoveis/'),
        ),
    ]
